name: Example CI

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running pre-commit hooks..."
      - uses: pre-commit/action@v3.0.0
      - name: Run Tests
        run: |
          ls
          echo "Running tests...."
